---
label: project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: title
- name: date
  type: datetime
  label: date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  default: ''
- name: description
  type: text
  config:
    required: false
  label: description
- name: images
  type: image_gallery
  config: {}
  label: images
- name: tag
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: tag
- name: categories
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: categories
